sensor:
  - platform: template
    sensors:
      lk_map:
        value_template: >
          {% set mapper =
            { 'Input_00':'Sensor_00',
              'Input_01':'Sensor_01',
              'Input_02':'Sensor_02',
              'Input_03':'Sensor_03',
              'Input_04':'Sensor_04',
              'Input_05':'Sensor_05',
              'Input_06':'Sensor_06',
              'Input_07':'Sensor_07',
              'Input_08':'Sensor_08',
              'Input_09':'Sensor_09',
              'Input_10':'Sensor_10',
              'Input_11':'Sensor_11',
              'Input_12':'Sensor_12',
              'Input_13':'Sensor_13',
              'Input_14':'Sensor_14',
              'Input_15':'Sensor_15',
              'Input_16':'Sensor_16',
              'Input_17':'Sensor_17',
              'Input_18':'Sensor_18',
              'Input_19':'Sensor_19',
              'Input_20':'Sensor_20',
              'Input_21':'Sensor_21',
              'Input_22':'Sensor_22',
              'Input_23':'Sensor_23',
              'Input_24':'Sensor_24',
              'Input_25':'Sensor_25',
              'Input_26':'Sensor_26',
              'Input_27':'Sensor_27',
              'Input_28':'Sensor_28',
              'Input_29':'Sensor_29',
              'Input_30':'Sensor_30',
              'Input_31':'Sensor_31',
              'Input_32':'Sensor_32',
              'Input_33':'Sensor_33',
              'Input_34':'Sensor_34',
              'Input_35':'Sensor_35',
              'Input_36':'Sensor_36',
              'Input_37':'Sensor_37',
              'Input_38':'Sensor_38',
              'Input_39':'Sensor_39',
              'Input_40':'Sensor_40',
              'Input_10':'Sensor_10',
              'Input_11':'Sensor_11',
              'Input_12':'Sensor_12',
              'Input_13':'Sensor_13',
              'Input_14':'Sensor_14',
              'Input_15':'Sensor_15',
              'Input_16':'Sensor_16',
              'Input_17':'Sensor_17',
              'Input_18':'Sensor_18',
              'Input_19':'Sensor_19',
              'Input_20':'Sensor_20',
              'Input_21':'Sensor_21',
              'Input_22':'Sensor_22',
              'Input_23':'Sensor_23',
              'Input_24':'Sensor_24',
              'Input_25':'Sensor_25',
              'Input_26':'Sensor_26',
              'Input_27':'Sensor_27',
              'Input_28':'Sensor_28',
              'Input_29':'Sensor_29',
              'Input_30':'Sensor_30',
              'Input_31':'Sensor_31',
              'Input_32':'Sensor_32',
              'Input_33':'Sensor_33',
              'Input_34':'Sensor_34',
              'Input_35':'Sensor_35',
              'Input_36':'Sensor_36',
              'Input_37':'Sensor_37',
              'Input_38':'Sensor_38',
              'Input_39':'Sensor_39',
              'Input_40':'Sensor_40',
              'Input_41':'Sensor_41',
              'Input_42':'Sensor_42',
              'Input_43':'Sensor_43',
              'Input_44':'Sensor_44',
              'Input_45':'Sensor_45',
              'Input_46':'Sensor_46',
              'Input_47':'Sensor_47',
              'Input_48':'Sensor_48',
              'Input_49':'Sensor_49',
              'Input_50':'Sensor_50',
              'Input_51':'Sensor_51',
              'Input_52':'Sensor_52',
              'Input_53':'Sensor_53',
              'Input_54':'Sensor_54',
              'Input_55':'Sensor_55',
              'Input_56':'Sensor_56',
              'Input_57':'Sensor_57',
              'Input_58':'Sensor_58',
              'Input_59':'Sensor_59',
              'Input_60':'Sensor_60',
              'Input_61':'Sensor_61',
              'Input_62':'Sensor_62',
              'Input_63':'Sensor_63',
              'Input_64':'Sensor_64',
              'Input_65':'Sensor_65',
              'Input_66':'Sensor_66',
              'Input_67':'Sensor_67',
              'Input_68':'Sensor_68',
              'Input_69':'Sensor_69',
              'Input_70':'Sensor_70',
              'Input_71':'Sensor_71',
              'Input_32':'Sensor_72',
              'Input_73':'Sensor_73',
              'Input_74':'Sensor_74',
              'Input_75':'Sensor_75',
              'Input_76':'Sensor_76',
              'Input_77':'Sensor_77',
              'Input_78':'Sensor_78',
              'Input_79':'Sensor_79' } %}
          {% set state = states('input_text.lk_pushbutton_lastpressed') %}
          {% set id = mapper[state] if state in mapper %}
          {{ id }}
