# MCP23017 Component
# .mcp23017_output_ju-demo-01
# The MCP23017 component allows you to use MCP23017 I/O expanders (datasheet,
#  Adafruit) in ESPHome. It uses the I²C Bus for communication.
#
# Once configured, you can use any of the 16 pins as pins for your projects. Within
# ESPHome they emulate a real internal GPIO pin and can therefore be used with
# many of ESPHome’s components such as the GPIO binary sensor or GPIO switch.
#
# GPIO pins in the datasheet are labelled A0 to A7 and B0 to B7, these are mapped
# consecutively in this component to numbers from 0 to 15.

switch:
# Individual output hub0
  - platform: gpio
    name: "Output_00"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_01"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_02"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_03"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_04"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_05"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_06"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_07"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 7
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_08"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 8
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_09"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 9
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_10"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 10
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_11"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 11
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_12"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 12
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_13"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 13
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_14"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_15"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 15
      mode:
        output: true
      inverted: false
# Individual output hub1
  - platform: gpio
    name: "Output_16"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_17"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_18"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_19"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_20"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_21"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_22"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_23"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 7
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_24"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 8
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_25"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 9
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_26"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 10
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_27"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 11
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_28"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 12
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_29"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 13
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_30"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_31"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 15
      mode:
        output: true
      inverted: false
# Individual output hub2
  - platform: gpio
    name: "Output_32"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_33"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_34"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_35"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_36"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_37"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_38"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_39"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 7
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_40"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 8
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_41"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 9
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_42"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 10
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_43"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 11
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_44"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 12
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_45"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 13
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_46"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Output_47"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 15
      mode:
        output: true
      inverted: false
